all:
  hosts:
    master:
      ansible_host: rsp1
      ansible_user: schelto
    worker1:
      ansible_host: rsp2
      ansible_user: schelto
    worker2:
      ansible_host: rsp3
      ansible_user: schelto

  children:
    master_group:
      hosts:
        master:
    worker_group:
      hosts:
        worker1:
        worker2:
